name: PR/CI Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # Use GitHub Environments to scope secrets: Production for main, Preview otherwise
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Preview' }}
    env:
      # Public config
      NEXT_PUBLIC_BASE_URL: https://tukang.design
      NEXT_PUBLIC_SANITY_PROJECT_ID: 330f0le5
      NEXT_PUBLIC_SANITY_DATASET: production
      NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
      # Fallback GA ID if secret not set
      GA_ID: G-13JMFQR6YB
      NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID != '' && secrets.NEXT_PUBLIC_GA_ID || env.GA_ID }}
      # Server secrets
      SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      CONTACT_TO: ${{ secrets.CONTACT_TO }}
      QUOTE_ACCEPTANCE_SECRET: ${{ secrets.QUOTE_ACCEPTANCE_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      # Optional: write minimal .env.local so Next.js reads values during build
      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> .env.local
          echo "NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID" >> .env.local
          echo "NEXT_PUBLIC_SANITY_DATASET=$NEXT_PUBLIC_SANITY_DATASET" >> .env.local
          if [ -n "${NEXT_PUBLIC_GTM_ID}" ]; then echo "NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID" >> .env.local; fi
          if [ -n "${NEXT_PUBLIC_GA_ID}" ]; then echo "NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID" >> .env.local; fi
          if [ -n "${RESEND_API_KEY}" ]; then echo "RESEND_API_KEY=$RESEND_API_KEY" >> .env.local; fi
          if [ -n "${EMAIL_FROM}" ]; then echo "EMAIL_FROM=$EMAIL_FROM" >> .env.local; fi
          if [ -n "${CONTACT_TO}" ]; then echo "CONTACT_TO=$CONTACT_TO" >> .env.local; fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build cache (optional)
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
